# Generated by Django 5.0.7 on 2024-08-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_costumer_store_costu_last_na_66ca2f_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
                          INSERT INTO store_collection(title)
                          VALUES ('collection1')
                          """, """
                          DELETE FROM store_collection
                          WHERE title='collection1' 
                          """)
    ]
