# Generated by Django 5.0.7 on 2024-08-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_promotions_alter_product_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='id',
        ),
    ]
