# Generated by Django 5.0.7 on 2024-08-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
