# Generated by Django 5.0.7 on 2024-08-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_taggeditem_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='object_id',
            field=models.CharField(max_length=10),
        ),
    ]
